FROM tensorflow/tensorflow:2.1.0-py3

ARG DOCKERVERSION=19.03.12
RUN apt-get update -y --fix-missing && \
    apt install -y git wget time && \
    python3 -m pip install numpy && \
    python3 -m pip install --upgrade pip && \
    python3 -m pip install absl-py && \
    python3 -m pip install sysv_ipc && \
    python3 -m pip install Pillow && \
    python3 -m pip install psutil && \
    apt-get install -y linux-tools-common linux-tools-generic linux-tools-`uname -r`