# FROM python:3.6-slim-stretch
FROM ubench_grpc_vs_lipc:latest

RUN apt-get update && \
    apt-get install -y curl software-properties-common && \
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add - && \
    apt-key fingerprint 0EBFCD88 && \
    add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" && \
    apt-get update -y && \
    apt-get install -y docker-ce docker-ce-cli containerd.io