#!/bin/bash


function main() {
    PWD=$(pwd)
    SCRIPTDIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
    COMMAND=$1
    GPU=0

    if [[ "$PWD" != "$SCRIPTDIR" ]]; then
        print_error "This script needs to be launched in its own root directory!\nexit"
        exit 1
    fi

    parse_arg "${@:2}"

    case $COMMAND in
        hello-world)
            cd ../applications/mobilenetv2
            # bash exp_script.sh latency-mon -n=1 --policy=$p --device=$DEVICE
            bash exp_script.sh latency -n=1 --policy=$p --device=$DEVICE
            cd - > /dev/null 2>&1
            ;;
        mobilenetv2)
            cd ../applications/mobilenetv2
            ./build-pockets.sh --all --gpu=${GPU}
            cd - > /dev/null 2>&1
            ;;
    esac
}

function parse_arg() {
    for arg in $@; do
        case $arg in
            --gpu=*)
                GPU=${arg#*=}
                DEVICE=$([[ $GPU = "1" ]] && echo gpu || echo cpu)
                ;;
            *)
                ;;
        esac
    done
}

_BOLD="\e[1m"
_DIM="\e[2m"
_RED="\e[31m"
_LYELLOW="\e[93m"
_LGREEN="\e[92m"
_LCYAN="\e[96m"
_LMAGENTA="\e[95m"
_RESET="\e[0m"


function print_error() {
    local message=$1
    echo -e "${_BOLD}${_RED}[ERROR]${_RESET} ${message}${_RESET}"

}

function print_warning() {
    local message=$1
    echo -e "${_BOLD}${_LYELLOW}[WARN]${_RESET} ${message}${_RESET}"

}

function print_info() {
    local message=$1
    echo -e "${_BOLD}${_LGREEN}[INFO]${_RESET} ${message}${_RESET}"

}

function print_debug() {
    local message=$1
    echo -e "${_BOLD}${_LCYAN}[DEBUG]${_RESET} ${message}${_RESET}"

}

main "$@"; exit